# DO NOT EDIT THIS FILE!! 
# IF MODIFIED IN ANY WAY, YOU WILL RECEIVE 0 FOR THE GRADE!
import math
import unittest
from Lab3 import polar_to_cartesian, cartesian_to_polar, pendulum_position

def test_polar_to_cartesian():
    assert polar_to_cartesian(1, 0) == (1, 0)
    assert polar_to_cartesian(1, 90) == (0, 1)
    assert polar_to_cartesian(2, 45) == (round(math.sqrt(2), 5), round(math.sqrt(2), 5))
    
def test_cartesian_to_polar():
    assert cartesian_to_polar(1, 0) == (1, 0)
    assert cartesian_to_polar(0, 1) == (1, 90)
    assert cartesian_to_polar(1, 1) == (round(math.sqrt(2), 5), 45.0)
    
def test_pendulum_position():
    assert pendulum_position(1, 1, 0, 0) == 1
    assert pendulum_position(2, 0.5, 90, 0) == 0
    assert pendulum_position(1, 1, 180, 0) == -1

if __name__ == '__main__':
    unittest.main()